trigger:
- master

pool:
  name: kunal-personal-pool

steps:
- script: |
    echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $HOME/.bashrc
    echo "PATH=$JAVA_HOME/bin:$PATH" >> $HOME/.bashrc
    source $HOME/.bashrc
  displayName: 'Set JAVA_HOME Environment Variable'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    jdkDirectory: '/usr/lib/jvm/java-11-openjdk-amd64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
  displayName: 'Build with Maven'
- task: CopyFiles@2
  inputs:
    Contents: '**/*.war'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'warfile'
    publishLocation: 'Container'
